### ISSUE TITLE
E-Mailing schedule crashes the server

### ISSUE THREAD

**Issue by Ryuno-Ki** [FOSDEM/volunteers#2]
Hi,

when I was done with picking the tasks I want to volunteer for, I went to my profile to get an overview of them.
At the bottom were two buttons for printing or e-mailing them. Printing works okay, but hitting the e-mail button crashed the server (as already reported on the volunteer mailing list).

I would have expected that the tasks get sent to the e-mail address I used for sign up.

**Comment by pieterdp** [comment]
Hi,

This should now be fixed (See #17 for the solution.)

Pieter
