### ISSUE TITLE
add ability to email people who are on a certain task

### ISSUE THREAD

**Issue by emanuil-tolev** [FOSDEM/volunteers#24]

**Comment by johanvdw** [comment]
This is already possible from the admin interface
* go to the /admin/volunteers/volunteer/ page
* on the right, filter by task or task category
* click select all and choose action: send mass mail

![image](https://user-images.githubusercontent.com/868434/107862995-180f6300-6e51-11eb-86cc-603f7c8e935c.png)

It is a bit counterintuitive you have to go to volunteer for this though, and not to task

**Comment by johanvdw** [comment]
This was also added to the task page: 
https://github.com/FOSDEM/volunteers/commit/50d8f176a6d9bb4ababc65d73d65da062c8e3bfe
