### ISSUE TITLE
Add file extension on download

### ISSUE THREAD

**Issue by Ryuno-Ki** [FOSDEM/volunteers#3]
Hi,

when I tried to download a page (since I couldn't email due to #2), I noticed that the file extension was missing.
This caused the file not have a handler on mobile.
After renaming the file and adding a „.pdf”, I could use my PDF viewer.
This is not needed on desktop.

**Comment by johanvdw** [comment]
Closed in: https://github.com/FOSDEM/volunteers/commit/d0b9610b5c15ccfbeaa2cea92eefa60d8a7120cd#diff-51877e1d8701435782239a1380c0ed28e353e8e3772db455b167e44e6f876693
