### ISSUE TITLE
FAQ: add a step by step guide for session host 

### ISSUE THREAD

**Issue by hpdang** [FOSDEM/volunteers#34]
Questions: What should I do as a session host? 
Answers:
As a host you will introduce the session, speaker(s), facilitate the Q&As. The pre-recorded video will play and end automatically on schedule. Below is a step-by-step guide: 
1. Make sure the speakers are in the session backstage at least 10 mins earlier than their scheduled time. If they are not there, search for them in the speakers channel or inform the organizers 
2. Introduce the session and speaker(s) from backstage 3-4 mins prior the schedule time. Invite the audience to type their questions and up-vote the questions. You can still introduce the session/speaker(s) even if the speakers are not around. 
3. Monitor the public stream while the video is playing. Report to the video team if there is any issue with the stream. 
4. Once the video ends, invite speakers to answer questions that show up on the top of the widget in backstage. 
5. Two minutes before the time is up, thank you speaker(s) and inform the speaker(s) and audience that the stream will be cut-off and but they are welcome to continue their conversation and Q&A in the backstage channel which will turn into hallway room once the session ends. You can share the link to the backstage with the audience.

**Comment by hpdang** [comment]
I'm working on this

**Comment by Danyc0** [comment]
I think this looks really good!
I could be wrong, but I don't think it's the backroom that turns into the hallway, I think a new room is created. Assuming it's running, the bot should post the link to the new hallway room in the chat when the time comes.
I was under the impression that you wouldn't be able to share a link to the backroom channel as they're meant to be private.

**Comment by hpdang** [comment]
@Danyc0 I actually don't know exactly what happens in the background, I just wrote it based what what the organizer told me in the volunteer channel. If you are sure, can you give a suggestion how I should update this?

**Comment by Danyc0** [comment]
Maybe change number 5 to be something like:
Two minutes before the time is up, thank you speaker(s) and inform the speaker(s) and audience that the stream will be cut-off but they are welcome to continue their conversation and Q&A in the hallway channel once the session ends. Near the end of the Q&A, the FOSDEM bot should share a link to hallway channel with the audience.

**Comment by hpdang** [comment]
#35

**Comment by Danyc0** [comment]
Sounds like I was indeed wrong about this! It looks great!
