### ISSUE TITLE
too many volunteers signup for task

### ISSUE THREAD

**Issue by schuhmi2** [FOSDEM/volunteers#38]
After a while, the volunteer tool _should_ stop people signing up if way too many people sign up.
Right now, eg for InfoDesk at 2021, it goes 5/3 = blue, then 6/3 = green.
Either it needs to stay blue, or stop further signups

**Comment by johanvdw** [comment]
You can set a maximum number for a task:

![image](https://user-images.githubusercontent.com/868434/107145880-e411da80-6944-11eb-9f37-5f8220d0aede.png)

It is weird though that 6 people could show up if the max number is 5

**Comment by johanvdw** [comment]
So the colorcode is: https://github.com/FOSDEM/volunteers/blob/master/volunteers/templates/volunteers/tasks.html#L62

- blue: full (>=max)
- gray: manageable (>min)
- red: volunteers needed
