### ISSUE TITLE
Show max size of image allowed

### ISSUE THREAD

**Issue by RAJAGOPALAN-GANGADHARAN** [FOSDEM/volunteers#40]
While adding details in https://volunteers.fosdem.org/volunteers this page, the image uploaded seems to be too large. Adding the upper bound of image size allowed will be really useful for people like me.

**Comment by johanvdw** [comment]
I will check what the sizes are.
It may also be that the reverse proxy enforces them.

**Comment by johanvdw** [comment]
If you received error 413, it probably means that the reverse proxy blocked it. It seems it will do this if the image is larger than 2 MB. I'll add a note.
