### ISSUE TITLE
Volunteer is asked to sign up to pentabarf in a confusing way

### ISSUE THREAD

**Issue by piemonkey** [FOSDEM/volunteers#58]
When volunteering for any task, a newly registered volunteer is prevented from doing so with an on-hover message saying "register penta account before subscribing". It's easy to see how to do this given there is a banner pushing to add one, but the message there is "Please register an account in pentabarf and add it to your details to enable hosting talks.".

Either the banner should be changed to say that a pentabarf is necessary for any volunteering, or if it's not, it shouldn't be required for people who are not hosting talks.

**Comment by johanvdw** [comment]
It's indeed an error, this was necessary for virtual editions. I'll try to remove it.

**Comment by johanvdw** [comment]
Registering in penta is now no longer necessary.
