### ISSUE TITLE
Issue in KDE Volunteers sign-in

### ISSUE THREAD

**Issue by vansh-goel** [FOSDEM/volunteers#61]
The KDE Akademy volunteers sign-in is not working, which is said to be based on this, I wanted to initially report to KDE itself, but couldn't find where to report an issue for the same, hence reporting it here.

![image](https://github.com/FOSDEM/volunteers/assets/62180044/698029a7-0b8f-467f-a942-93f926bc53bb)

**Comment by markvdb** [comment]
I'm afraid you'll have to report this elsewhere. Unfortunately, we can't help you with that.

**Comment by vansh-goel** [comment]
Ah alright, thanks for checking the issue out
