### ISSUE TITLE
Volunteer Image Upload is not Functional

### ISSUE THREAD

**Issue by TildaDares** [FOSDEM/volunteers#62]
When I tried to upload a profile picture to my volunteer profile, I got the following error:

```
Site crashed
Sorry for the inconvenience.

Please take the time to report an issue at Github so it doesn't happen again.
```

Text update works fine so this issue is an isolated one for just image uploads.

A screenshot of the error page is attached below:

<img width="610" alt="Screenshot 2023-11-13 at 14 32 26" src="https://github.com/FOSDEM/volunteers/assets/63427719/31a1d0b0-2f60-43f7-ae89-c1055156e690">

**Comment by emanuil-tolev** [comment]
Hey fosdemers, long time no see :). I can't fix this but I still get the errors cc-d so can provide a clue:

> Exception Type: PermissionError at /volunteers/[redacted]/edit/
Exception Value: [Errno 13] Permission denied: '[path prefix redacted]/fosdem_volunteers/tool/public/media/mugshots/[redacted].jpg'

Check the directory permissions of the above mugshots dir :).

**Comment by johanvdw** [comment]
Note that some stuff is not yet correct on the volunteers site, especially anything regarding pentabarf should be ignored, as we are using pretalx this year.

**Comment by emanuil-tolev** [comment]
Ok I updated mine successfully. @TildaDares let us know if it's working for you now :).

**Comment by RichiH** [comment]
Are... are you back, @emanuil-tolev ?

**Comment by emanuil-tolev** [comment]
> I believe I fixed the permissions on that dir. I do am quite suprised that mails are sent on errors, never knew about that feature.

Ok so it's actually sending to the volunteer-admin list of which I'm still a member I guess. I can't find the setting in the (public at least) config tho.

**Comment by TildaDares** [comment]
I can update my profile picture now. Thanks!

**Comment by kergon** [comment]
On Mon, Nov 13, 2023 at 08:20:02AM -0800, Emanuil Tolev wrote:
>    Ok so it's actually sending to the volunteer-admin list of which I'm still
>    a member I guess. I can't find the setting in the (public at least) config
>    tho.

(You aren't on that list any more.)

Alasdair

**Comment by kergon** [comment]
You were listed in one of the config files though - I've updated this.

Alasdair
