### ISSUE TITLE
Overlapping tasks of the same type in the same location shouldn't cause conflict

### ISSUE THREAD

**Issue by thibaultmol** [FOSDEM/volunteers#77]
I was having an issue just like the user in issue https://github.com/FOSDEM/volunteers/issues/74
Where I was signed up for two video tasks after each other, which overlap. But because both of the tasks are assigned to me, it shouldn't cause the warning

**Comment by Danyc0** [comment]
Can you link me to your two overlapping tasks?

**Comment by thibaultmol** [comment]
![image](https://github.com/FOSDEM/volunteers/assets/1010226/46439db1-c8cf-45b1-964c-e815d9caddf5)
https://volunteers.fosdem.org/task/1274/
https://volunteers.fosdem.org/task/1275/
