### ISSUE TITLE
On mobile UI: you can't see which room/building it is

### ISSUE THREAD

**Issue by thibaultmol** [FOSDEM/volunteers#79]
So if you're on the mobile version of the website you can't see the difference between certain tasks.
There is no field to show the location.
So if you're signed up for certain tasks like 'volunteer pool', you can't tell which location it is.
![image](https://github.com/FOSDEM/volunteers/assets/1010226/9d887f9a-58ca-408d-816b-8291254b8b4a)

You can on the desktop ui, but not the mobile ui

**Comment by Danyc0** [comment]
Can you provide a screenshot of the location being shown on desktop? I can't see it anywhere myself

**Comment by thibaultmol** [comment]
Ignore this, made this issue was I was too tired probably. cloakroom is always in K and volunteer pool doesn't have location (duh)
